### 넘파이 
numpy는 tensorflow의 핵심 자료구조

In [1]:
# list
my_list = [1,2,3,4,5]
my_list2 = [10,20,30,40,50]

print(my_list)
print(my_list[1])

[1, 2, 3, 4, 5]
2


In [2]:
#물리적으로 더해짐
print(my_list + my_list2)
# 물리적으로 2배가 됨
print(my_list * 2)

#즉, 파이썬의 list 자료구조는
# 백터 연산에 적합하지 않음

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [ ]:
# 만일 my_list의 각 요소 값을 2배로 하고 싶으면?
# [1,2,3,4,5] -> [2,4,6,8,10]
# for문을 돌려야함
result1 = [i*2 for i in my_list]
result2 = []
for i in my_list:
    result2.append(i * 2)
print(result1)
print(result2)
# -> 수학 연산 번거롭고 오래걸린다,,

# 그래서 numpy 수학 연산을 위한 모듈의 넘파이 배열 사용함
# TensorFlow도 텐서기반, PyTorch도 텐서기반
# 모두 기반이 numpy 배열

[2, 4, 6, 8, 10]
[2, 4, 6, 8, 10]


numpy는 파이썬의 기본 내장 모듈이 아니라서
따로 패키지 설치/임포트가 필요하다.

* 가상환경(.venv)생성 
python -m venv .venv
* 가상환경 활성화
source .venv/bin/activate
* numpy 모듈 설치
pip install numpy

* uv 도구 사용 시
uv add numpy



In [4]:
import numpy as np

In [ ]:
#numpy는 어떻게 만들까?
# list를 가지고 만든다
#np.array(list)

my_list = [0,1,2,3,4]
print(type(my_list))#<class 'list'>

my_numpy = np.array(my_list)
print(type(my_numpy))# <class 'numpy.ndarray'>

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
print(my_numpy)#[0 1 2 3 4]
print(my_list)#[0, 1, 2, 3, 4]

# 출력 시 
# list는 ,로 각 요소 구분
# numpy배열은 , 없이 공백으로 구분됨

[0 1 2 3 4]
[0, 1, 2, 3, 4]


In [9]:
#list를 만들듯이 공백으로 구분해서 numpy를 만들 수 있을까?
#my_np = [1 2 3 4 5]
#SyntaxError: invalid syntax. Perhaps you forgot a comma?

#안된다

In [ ]:
# numpy를 만들 땐,
# list를 통해서 만들던지 : np.array(list) numpy배열로 변환
# arr = np.arange(1,6)로 범위 생성해서 만들던지
# np.zeros(5) 모든 요소가 0인 넘파이배열 
# np.ones(5) 모든 요소가 1인 넘파일 배열
# np.random.rand(5) 랜덤 넘파이 배열
# 이렇게는 지원이 된다고,,


#PyTorch/TensorFlow도 본질은:
#거대한 다차원 NumPy 배열 계산

* 백터 연산 : 배열 내부 요소끼리의 연산을 말함
- 스칼라 : 값이 1개
- 백터 : 1차원 배열
- 행렬(matrix) : 2차원배열
- 텐서 : n차원 배열(3차원 이상의 다차원배열) 

* 백터 연산 같은 경우에, 
같은 위치의 원소들끼리 연산을 수행하기 때문에 빠르다.

백터 a,b가 있다고 가정
a = [1 2 3]
b = [4 5 6]

이 때, 두 벡터의 합을 계산
-> 같은 위치의 원소끼리 더해주면 된다.
a + b = [1+4, 2+5, 3+6] = [5,7,9]

이렇게 배열 내부 요소끼리의 연산을 의미하는
백터 연산을 이용하면 간단하면서도 빠르게 많은 데이터를 처리할 수 있음
-> numpy배열은 이런 백터연산을 지원하기 때문에
 데이터 분석 분야에 많이 사용됨


In [ ]:
#list와 numpy배열 비교
list1 = [1,2,3]
list2 = [4,5,6]

print(f"리스트연산:{list1+list2}")
#[1,2,3,4,5,6]

np1 = np.array(list1)
np2 = np.array(list2)
print(f"numpy(백터)연산:{np1+np2}")#내부 요소들끼리 더해짐
#[5,7,9]


리스트연산:[1, 2, 3, 4, 5, 6]
numpy(백터)연산:[5 7 9]


In [ ]:
data = [0,1,2,3,4,5,6,7,8,9]
# 각 요소를 2배 해야되는 경우라면?
#list의 경우
result = []
for i in data:
    result.append(i * 2)
print(result)#[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

#또는
result2 = [i * 2 for i in data]
print(result2)#[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

#numpy 경우
arr = np.array(data)#list -> numpy배열로 변환
#arr = [1 2 3 4 5 6 7 8 9]
print(arr)#[0 1 2 3 4 5 6 7 8 9]

arr = arr * 2
print(arr)#[ 0  2  4  6  8 10 12 14 16 18]


[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]


In [14]:
a = np.array([1,2,3])
b = np.array([10,20,30])

print(a)#[1 2 3]
print(b)#[10 20 30]

print((2 * a) + b)
#[12 24 36]

[1 2 3]
[10 20 30]
[12 24 36]


In [ ]:
# 백터 연산 - 비교 연산자: 원소별 비교 연산함
# 각 요소들을 비교해서 같으면 True, 다르면 False
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(a == 2)
#넘파이배열 각 요소가 2와 같은지 비교함
#[False True False]

[False  True False]


In [17]:
print(b > 10)
#각 요소가 10보다 큰지 비교
#[False True Ture]

[False  True  True]


In [ ]:
print((a == 2) & (b > 10))
#[False True False]

#numpy에서는 and연산을 &사용함
# | or연산
# ~ not연산
#연산자 우선순위가 있으므로, ()사용 필수

[False  True False]


In [ ]:
#흑백이 2차원, 컬러가 3차원, 동영상이 4차원 뼈대 쓴다고 함