In [2]:
import numpy as np

In [3]:
#2차원 numpy 배열 
n = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(n)
print(type(n))
n

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#2차원 배열의 행과 열의 갯수
a = np.array([[1,2],
              [2,3],
              [4,5],
              [6,7]])
print(len(a)) #4
#행의 갯수: 2차원 배열에 들은 1차원 요소 개수

print(len(a[0])) #2
#열의 개수: 0번째 1차원의 요소개수

#실제 데이터를 읽어오는 것은
# 대부분 2차원 배열이라고 함



4
2


In [8]:
#3차원 배열:
# 2차원 배열을 요소로 가지고 있는 배열
b = np.array([
                [
                    [1,2,3,3],
                    [3,4,5,4],
                    [1,2,3,3]
                ],
                [
                    [10,20,30,40],
                    [30,20,1,11],
                    [7,7,7,7]
                ]
              ])

# 2 * 3 * 4 
# 쪽 * 행 * 열

print(len(b))#2
print(len(b[0]))#3
print(len(b[0][0]))#4


2
3
4


In [ ]:
#(중요) 넘파이 배열의 차원과 크기 알아내기
# ndim속성과 shape속성 이용
# ndim 속성: 배열의 차원
# shape 속성: 배열의 크기 튜플로 반환

a = np.array([[10,20,30,40],[50,60,70,80]])
print(a.ndim) #2 : 2차원이라는 뜻
print(a.shape)#(2,4) 2*4행렬이라는 뜻




2
(2, 4)


In [10]:
d = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
              [[11, 12, 13, 14],
               [15, 16, 17, 18],
               [19, 20, 21, 22]]])   # 2 x 3 x 4 array

print(d.ndim)#3 : 3차원
print(d.shape)#(2,3,4) 2*3*4 

3
(2, 3, 4)


In [11]:
#numpy 배열의 인덱싱
a = np.array([1,2,3,4,5])
print(a[-1])#5
print(a[3])#4

5
4


In [ ]:
b = np.array([[0,1,2],[3,4,5]])
print(b)
print(b[-1][-1])#5
print(b[0][0])#0
print(b[0][1])#1


[[0 1 2]
 [3 4 5]]
5
0
1


In [14]:
#(중요) numpy배열 슬라이싱
# 데이터를 가져올 때 배열 슬라이싱 사용하게 된다
# AI 모델링을 하게 되면
# 행으로는 1,2,5천개 등 엄청 많은 큰 데이터 가져오고
# 열은 속성(feature)이라고 하는 것 
# 정답 클래스(label) 가져오는 것
# 이렇게 속성과 클래스를 구분하기 위해서도 슬라이싱으로 가져오고
# 천개의 데이터가 있으면
# 그 중에서 800개로 학습하고
# 200개로 검증하기 위해서 나눌 때도 배열 슬라이싱이 사용됨

a = np.array([[0,1,2,3],[4,5,6,7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
a[0,:]#0번째행, 모든 열 
# :을 기준으로 시작:끝 인데
# 비어있으면 처음부터끝까지 전체

array([0, 1, 2, 3])

In [16]:
a[:,0:2]#모든행, 0~1행까지(2직전까지)

array([[0, 1],
       [4, 5]])

In [17]:
a[:,1]

array([1, 5])

In [ ]:
a[1,1:] #인덱스1번행, 인덱스1부터모든열
#[5 6 7]

array([5, 6, 7])

In [ ]:
a[:2,:2]#인덱스0~1행, 0~1열
#[[0 1], [4 5]]


array([[0, 1],
       [4, 5]])

In [26]:
#문제
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])

# 행렬에서 값 7 인덱싱
print(m[1][2])
# 행렬에서 값 14 인덱싱
print(m[2][4])
print(m[-1][-1])
# 배열 [6 7] 슬라이싱
print(m[1,1:3])
# 배열 [7 12] 슬라이싱
print(m[1:,2])
# 배열 [[3 4],[8 9]] 슬라이싱
print(m[:2,3:])


7
14
14
[6 7]
[ 7 12]
[[3 4]
 [8 9]]


In [ ]:
#fancy indexing
# 배열로도 인덱싱이 가능함

#bool배열로 인덱싱
a = np.array([0,1,2,3,4,5,6,7,8,9])
idx = np.array([True,False,True,False,True,False,True,False,True,False])

print(a)
print(idx)
print(a[idx])#[0 2 4 6 8]
# True인 위치와 같은 요소만 살아남음

[0 1 2 3 4 5 6 7 8 9]
[ True False  True False  True False  True False  True False]
[0 2 4 6 8]


In [ ]:
#조건문으로도 인덱싱 가능
print(a % 2)#[0 1 0 1 0 1 0 1 0 1]
print(a % 2 == 0)#[ True False  True False  True False  True False  True False]
print(a[a % 2 == 0])#[0 2 4 6 8]

[0 1 0 1 0 1 0 1 0 1]
[ True False  True False  True False  True False  True False]
[0 2 4 6 8]


In [33]:
#정수인덱스로 인덱싱
a = np.array([11,22,33,44,55,66,77,88,99])
idx = np.array([0,2,4,6,8])
print(a[idx])# 0,2,6,8번 인덱스에 있는 요소 가져옴
#[11 33 55 77 99]

#bool배열일 때는 True인 위치와 같은 요소만 가져오는거고
#정수배열일 때는 해당하는 값이 인덱스가 되는것

[11 33 55 77 99]


In [ ]:
a = np.array([11,22,33,44,55,66,77,88,99])
idx = np.array([1,1,1,1,1,2,2,2,2,0,0,0,0])
print(a[idx])#[22 22 22 22 22 33 33 33 33 11 11 11 11]
#인덱스 1,1,1,1,1,2,2,2,2,0,0,0,0에 해당하는값 가져옴


[22 22 22 22 22 33 33 33 33 11 11 11 11]


In [35]:
#다차원 배열의 각 체원에 대해서도 할 수 있음
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a[:,[True,False,False,True]]
#모든행, True에 해당하는 열만 가져옴
#[[1 4],[5 8],[9 12]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [37]:
a[[2,0,1],:]
#행 2,0,1에 해당하는 요소, :모든열
#[[ 9 10 11 12],
# [1 2 3 4],
# [5 6 7 8]]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [ ]:
#(중요)넘파이의 자료형
#배열의 자료형을 확인하는 속성
# numpy배열.dtype

x = np.array([1,2,3])
print(x.dtype)#int64
print(x.ndim)#1
print(x.shape)#(3,)
#1차원배열 shape : (요소개수,)
#2차원배열 shape: (행개수, 열개수)

#x 타입이 64비트 정수인데
# csv파일에서 샘플 데이터를 읽어왔다하면
# 열어서 확인하기 전엔 데이터 타입 모른다,,



int64
1
(3,)


In [ ]:
x = np.array([0.1,0.2,3.4,1.1])
print(x.dtype)#float64

#float는 데이터타입 실수를 의미하고
#64비트 메모리에 저장되는 크기
#1바이트는 8비트
#8바이트 크기를 가지는 실수
#정수 64비트이면 엄청 큰값을 표시하는 길이를 가질 수 있음
#64비트 실수면 뒤의 소수점을 굉장히 많이 표현 가능

#만약에, 정수와 실수가 섞여있는 배열이면?
x = np.array([0,1,3.4])
x.dtype #dtype('float64')
#만약 정수 취급하면 소수자리수가 날아가기 때문에
# 값 손해보지 않으려면
# 정수를 실수로 만듬
# 그래서 float64 실수
print(x)#[0.  1.  3.4]
print(x[0],x[1],x[2])#0.0 1.0 3.4
#이렇게 자동 형변환
#넘파이배열은 꼭 같은 데이터타입이여야한다.

float64
[0.  1.  3.4]
0.0 1.0 3.4


| dtype 접두사 | 설명 | 사용 예시 | 실제 할당 크기 (비트) | 실무적 용도 및 특징 |
|---|---|---|---|---|
| b | 불리언(Boolean) | `b` | 8비트 (1바이트) | 참(True) 또는 거짓(False) 조건식 결과 저장 |
| i | 정수(Integer) | `i8` | 64비트 (8×8) | 음수(−), 0, 양수(+)를 모두 표현하는 일반 정수 계산 |
| u | 부호 없는 정수(Unsigned Integer) | `u8` | 64비트 (8×8) | 0과 양수만 표현하는 대신, 플러스 방향으로 2배 더 큰 숫자 저장 가능 (이미지 픽셀 등) |
| f | 부동소수점(Float) | `f8` | 64비트 (8×8) | 소수점이 포함된 실수 연산 (딥러닝 오차 및 가중치 계산의 기본 체급) |
| c | 복소 부동소수점(Complex Float) | `c16` | 128비트 (16×8) | 실수부와 허수부가 공존하는 고등 과학 계산 및 공학 시뮬레이션용 |
| o | 객체(Object) | `o` | 시스템 주소 크기 | 파이썬의 리스트, 딕셔너리 등 순수 파이썬 객체의 주소를 직접 가리킬 때 사용 |
| S | 바이트 문자열(Bytes String) | `S24` | 24×8 비트 | 알파벳과 숫자 중심의 옛날 문자열 저장 방식 (1글자당 1바이트) |
| U | 유니코드 문자열(Unicode String) | `U24` | 24×32 비트 | 한글, 한자, 이모티콘 등 전 세계 언어가 깨지지 않는 현대 표준 방식 (1글자당 4바이트) |

In [45]:
x = np.array([1,2,3],dtype='f')
x.dtype#dtype('float32')
print(x[0]+x[1])#3.0

3.0


In [ ]:
#Inf와 NaN
#Inf:무한대, -Inf:음의 무한대
#NaN:숫자가 아니다, 정의 불가
#발산하는 경우에는 NaN
# 파이썬이 표현할 수 있는 숫자 범위를 넘어서면
# NaN이 나옴
# 모델링하다가 가끔 보인다고 함//-> 안좋은 경우임

a = np.array([1.0,2.0,-3.0,0.0])
b = np.array([0.0,1.0,0.0,0.0])
#양수를 0으로 나누면 Inf
#음수를 0으로 나누면 -Inf
#numpy에서는 0으로 나눠도 예외안남
#(다른언어에서는 예외터짐)

#1을 0.1로 나누면 10이되고,
#10을 0.01로 나누면 100이되고
#0.001로 나누면 1000이되고
#0.000000000000000000000000001로 나누면
# 엄청 커져서 무한대
# 이게 0에 가까워질수록 무한대가 나오기 때문에
# 0으로 나누면 +무한대
# -0으로 나누면 마이너스 무한대
#0을 0으로 나누는건 허용하지 않아서
#NaN이 된다고 함
c = a / b
print(c)#[ inf   2. -inf  nan]

[ inf   2. -inf  nan]


C:\Users\user\AppData\Local\Temp\ipykernel_8524\3087323149.py:26: RuntimeWarning: divide by zero encountered in divide
  c = a / b
C:\Users\user\AppData\Local\Temp\ipykernel_8524\3087323149.py:26: RuntimeWarning: invalid value encountered in divide
  c = a / b


In [ ]:
#numpy배열 생성
#zeros함수: 모든 요소 값이 0인 배열 생성
# 아규먼트에는 배열의 크기를 뜻하는 정수/튜플을 넣는다
a = np.zeros(5)
a.dtype#dtype('float64')

dtype('float64')

In [ ]:
print(a)#[0. 0. 0. 0. 0.]

[0. 0. 0. 0. 0.]


In [ ]:
print(a.ndim, a.shape)#1 (5,)

1 (5,)


In [53]:
b = np.zeros((3,5))#3*5 2차원배열생성(모든요소가 0인)
print(b)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#array()와 마찬가지ㅣ로, dtype을 아규먼트로 설정하면
# 해당 자료형 원소를 가진 배열로 생성한다
c = np.zeros((2,3), dtype='i')
print(c)
print(c.dtype)#int32

[[0 0 0]
 [0 0 0]]
int32


In [ ]:
d = np.zeros(3,dtype='U4')
#텅빈 문자열 
print(d)#['' '' '']
print(d.dtype)#<U4

#데이터보다 dtype이 담을 수 있는 크기가 작으면
#데이터가 잘린다

['' '' '']
<U4


In [ ]:
#ones(): 1로 초기화된 배열 생성
e = np.ones((2,3,4), dtype='i8') #i8:8바이트 정수
#정수형으로 2*3*4 구조의 3차원배열 생성(모든 요소가 1인)
print(e)
print(e.dtype)#int64

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
int64


In [61]:
#zeros_like: 참조할 배열과 같은 구조로 만드는데, 모든 요소를 1로
#ones_like: 참조할 배열과 같은 구조로 만드는데, 모든 요소를 0로
c

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [67]:
f = np.zeros_like(c, dtype='f')
f

array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [66]:
f = np.ones_like(c, dtype='f')
f

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [ ]:
#empty(): 튜플로 배열 크기 넣어주면
# 생성하는데 기존에 메모리에 저장되어있던 값(쓰레기데이터)으로 
g = np.empty((2,3))
g

array([[ 1.79769313e+308, -1.79769313e+308,  2.00000000e+000],
       [ 2.22044605e-016,  2.22507386e-308,  4.94065646e-324]])

In [ ]:
#arange명령
z = np.arange(10)
z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
t = np.arange(3,10,2)#시작, 끝(직전까지), step
t

array([3, 5, 7, 9])

In [73]:
#linspace: 구간을 균등하게 나눠서 숫자 생성, 등차증가
#logspace: 로그 긴격으로 숫자생성, 등비증가

#np.linspace(start, stop, num)
# 시작, 끝(포함), 몇개생성할지

#np.logspace(start, stop, num)

np.linspace(0,100,5)
#0부터 100까지 5구간으로 나눠라

array([  0.,  25.,  50.,  75., 100.])

In [74]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [ ]:
np.logspace(0.1,1,10)
#0.1부터 1사이의 값을 내부적으로 10등분
#이 값을 log로 하기 위해서
# 10의 0.1승... 이렇게..
# log값도 균등하게 분할해서 표시할 수 있다,,

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

In [76]:
#전치 연산
# 행렬 곱을 할 때
# 첫번쨰 행렬의 열과
# 두번째 행렬의 행의 크기가 같아야 연산이 가능함
# 그럴때 전치연산 활용

#전치연산은 행과 열을 바꿔주는 작업
#나중에 트랜스포머 디코더가 전치연산을 통해서
# 어텐션이라고 하는 메커니즘을 구현할 때가 있다고
# 그때 보게된다고 함

In [ ]:
#(중요) ai에 많이 사용됨
#reshape() 
#배열의 크기 변형
a = np.arange(10)
#0~9까지 10개의 요소를 가진 넘파이 배열 생성
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
b = a.reshape(2, 5)
b
#요소 10개인 a배열을 2행 5열로 만들겠다
# 5개씩 2묶음
# 2 * 5 = 10 이라 가능
# (3,4)로하면 요소 10개를 3행 4열로 못만드니까
# 에러남

#reshape() : 메모리에 있는 요소는 그대로, 방 구조만 바꿈
# 원래 배열의 총 요소 개수와 
# 변환할 차원의 총 곱(행 * 열)이 일치해야 연산 성립
# (3,4)로 하면 2개가 부족함 ValueError


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [84]:
#ai모델링 할때 -1를 쓴다고함
# -1 : 나머지 컴퓨터 너가 계산해서 할당해라 의미
a.reshape(-1, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [85]:
b = np.arange(12)#0~11 총 12개요소 1차원배열생성
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
b.reshape(2,2,-1)#2쪽, 2행으로 하고 열은 너가 자동계산해라

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [ ]:
#flatten() : 다차원 배열을 1차원 배열로 "복사"해서 반환
# 원본은 안바뀐다는 뜻
arr = np.array([
    [1,2],
    [3,4]
])
print(arr.shape)#(2,2)

f = arr.flatten()#복사해서 1차원으로 펼침
print(f)#[1,2,3,4]
print(f.shape)#(4,) 1차원 백터


(2, 2)
[1 2 3 4]
(4,)


In [ ]:
#ravel(): 1차원으로 펼침, 원본 메모리 공유,
# 즉 r로 접근해 값 수정 시 원본 바뀜
print(arr)
r = arr.ravel()#원본변경 1차원으로 펼침
print(r)#[1 2 3 4]

#복사하기 때문에 ravel()이 flatten()보다 빠르지만
# 원본이 수정 위험이 있음
# 원본 보호가 필요하면 flatten()사용


[[1 2]
 [3 4]]
[1 2 3 4]
[[1 2]
 [3 4]]
